# To build the entire stack run 'make run'
version: '3.4'

services:
  reactle:
    container_name: reactle
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
