# To build the entire stack run 'make run'
version: '3.4'

services:
  reactle:
    container_name: reactle
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 8999:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/8999"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s