apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: devops

build:
  artifacts:
  - image: reactle
    context: .

profiles: 
  - name: dev 
    activation: 
      - command: dev
    build: 
      artifacts: 
      - image: reactle 
        context: .
        docker:
          dockerfile: docker/Dockerfile
          buildArgs: 
            ENV: development
        sync: 
          manual: 
          - src: 'src/**/**'
            dest: .
deploy:
  kubectl:
    manifests:
    - k8s/reactle-deployment.yaml
    - k8s/reactle-service.yaml
portForward:
  - resourceType: deployment
    resourceName: reactle
    port: 3000
    localPort: 9000 # *Optional*