apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: reactle
  name: reactle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reactle
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: reactle
    spec:
      containers:
        - image: reactle
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          name: reactle
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
